### ISSUE TITLE
Can't create Identity user

### ISSUE THREAD

**Issue by benduongquangmobile** [getsocial-im/getsocial-react-native-sdk#26]
it always errors

```
    const userId = 1234; // get user ID on your login provider
    const accessToken =
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyMzQsImlhdCI6MTUxNjIzOTAyMiwiZXhwIjoxNjcyNTMxMTk5fQ.hYNrS-Coz4DM3N-Hv2wkTPo764XMgjz71LLj1mMX3Po';
    const identity = Identity.createCustomIdentity(
      'my_auth_system',
      userId,
      accessToken,
    );
    const currentUser = await GetSocial.getCurrentUser();
    currentUser.addIdentity(
      identity,
      () => {
        console.log('Successfully logged into ' + userId);
      },
      (conflictUser: any) => {
        console.log('conflictUser', conflictUser);
      },
      (error: any) => {
        console.log('Failed to log into ' + userId);
        console.log('error', error);
      },
    );
```

```
error Error: Failed to parse attribution of class im.getsocial.sdk.communities.Identity having: 1234
    at Object.promiseMethodWrapper [as callAsync] (NativeModules.js:106)
    at User.addIdentity (CurrentUser.js:53)
    at _callee$ (VM5 App.bundle:38)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:294)
    at Generator.next (runtime.js:119)
    at tryCatch (runtime.js:63)
    at invoke (runtime.js:155)
    at runtime.js:165
    at tryCallOne (core.js:37)
```

**Comment by gaborvass** [comment]
hi,
`userId` parameter is a `String`, so you need to define it like this:
`const userId = '1234';`

**Comment by benduongquangmobile** [comment]
I edit userId to string and have this error

```
    const userId = '1234'; // get user ID on your login provider
    const accessToken =
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0IiwiaWF0IjoxNTE2MjM5MCwiZXhwIjoxNzMyNDcxNDcyfQ.5C0q3KY0BjfC3Y6Y93f4_IgNju9BOvk84tLrn9DP_8M';
    const identity = Identity.createCustomIdentity(
      'my_auth_system',
      userId,
      accessToken,
    );
    const currentUser = await GetSocial.getCurrentUser();
    currentUser.addIdentity(
      identity,
      () => {
        console.log('Successfully logged into ' + userId);
      },
      (conflictUser: any) => {
        console.log('conflictUser', conflictUser);
      },
      (error: any) => {
        console.log('Failed to log into ' + userId);
        console.log('error', error);
      },
    );
```

```
error Error: Invalid JWT access token.
    at Object.promiseMethodWrapper [as callAsync] (NativeModules.js:106)
    at User.addIdentity (CurrentUser.js:53)
    at _callee$ (VM5 App.bundle:31)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:294)
    at Generator.next (runtime.js:119)
    at tryCatch (runtime.js:63)
    at invoke (runtime.js:155)
    at runtime.js:165
    at tryCallOne (core.js:37)
```

**Comment by demiandenker** [comment]
> eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0IiwiaWF0IjoxNTE2MjM5MCwiZXhwIjoxNzMyNDcxNDcyfQ.5C0q3KY0BjfC3Y6Y93f4_IgNju9BOvk84tLrn9DP_8M

Make sure that the JWT is signed with the Shared Secret of your app that is available in the GetSocial Dashboard.
For more information check the documentation [here](https://docs.getsocial.im/guides/user-management/identify-users/#add-a-custom-trusted-identity)

**Comment by benduongquangmobile** [comment]
I stick with the documentation clearly. I use the parameter almost the same, but still getting errors like above.

**Comment by demiandenker** [comment]
The error is thrown because the JWT is not correctly signed. Could you please reach us through the support chat in your GetSocial Dashboard so we can follow up? We need information about your app that we can't ask you over here. Thanks

**Comment by demiandenker** [comment]
Sorry, but can only provide support through our support channel inside the GetSocial Dashboard. Log in with your account and contact us by clicking the `?` on the top right.

**Comment by benduongquangmobile** [comment]
is this a bug?
https://user-images.githubusercontent.com/92382730/142341716-21ae28aa-a87a-4dcc-a0f7-89b613bd614f.mov

**Comment by demiandenker** [comment]
Hi, it's not a bug, check that you don't have any browser extension blocking the support chat.

In any case, as I mentioned before, the problem you have with the JWT is that it is **NOT** correctly signed with the `Shared Secret` available in the [App Settings](https://dashboard.getsocial.im/#/app-settings) section of your GetSocial Dashboard.

You can manually create a valid JWT using this website: https://jwt.io/ and pasting your `Shared Secret` in the Verify Signature section (where it asks for `your-256-bit-secret`). Then replace the generated JWT in your code.

I've just tested the same and was able to authenticate/add identity using the correctly signed JWT with your `Shared Secret`. 

Regards,

**Comment by benduongquangmobile** [comment]
I run this to create a user, it doesn't show any error or success log, and the dashboard 
doesn't store it.

```
    try {
      const userId = '123444444'; // get user ID on your login provider
      const accessToken =
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NDQ0NDQiLCJpYXQiOjE1MTYyMzkwLCJleHAiOjE3MzI0NzE0NzJ9.C390FUi7VSJ6Bzohl7hiB8c5QLnRqAV4nOBmKB0YuYs';
      const identity = Identity.createTrustedIdentity(
        'twitter',
        userId,
        accessToken,
        true,
      );
      const currentUser = await GetSocial.getCurrentUser();
      currentUser.addIdentity(
        identity,
        () => {
          console.log('Successfully logged into ' + userId);
        },
        conflictUser => {
          console.log('conflictUser', conflictUser);
        },
        error => {
          console.log('Failed to log into ' + userId);
        },
      );
    } catch (error) {
      console.log(error);
    }
```


<img width="1022" alt="Screen Shot 2021-11-19 at 10 43 04" src="https://user-images.githubusercontent.com/92382730/142561234-3e4f085e-40fb-469c-8917-35f70584d67e.png">
.

**Comment by benduongquangmobile** [comment]
I removed all extensions, still can't click on the support

https://user-images.githubusercontent.com/92382730/142583894-ed475e2e-7b36-4ab4-87aa-7a99c1f42055.mov

**Comment by demiandenker** [comment]
I've removed your previous message because it contained sensitive information about your app. 

You are still having problems with the JWT generation, it is NOT correctly signed.
The correct JWT, in this case, would be 
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NDQ0NDQiLCJpYXQiOjE1MTYyMzkwLCJleHAiOjE3MzI0NzE0NzJ9.RL2comkYovKpvjogMPYa7AcIq8_0Vg6F4-vuX3oH6m8`

<img width="1205" alt="Screenshot 2021-11-19 at 09 17 04" src="https://user-images.githubusercontent.com/299897/142589138-8c8a8b5b-b73e-4f93-a4ed-7f4e9b2cf6ab.png">

Regarding your code, take in mind that when using Trusted Identities the code is slightly different as stated in the [documentation](https://docs.getsocial.im/guides/user-management/identify-users/#add-a-custom-trusted-identity).

```
const identity = Identity.createTrustedIdentity('twitter', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NDQ0NDQiLCJpYXQiOjE1MTYyMzkwLCJleHAiOjE3MzI0NzE0NzJ9.RL2comkYovKpvjogMPYa7AcIq8_0Vg6F4-vuX3oH6m8');
const currentUser = await GetSocial.getCurrentUser();
currentUser.addIdentity(
    identity,
    () => { console.log('Successfully logged); },
    (conflictUser) => { console.log(conflictUser); },
    (error) => { console.log('Failed to log into'); }
);
